### ISSUE TITLE
Extend to 3D

### ISSUE THREAD

**Issue by LearnerCFD** [JonHall101/CUDA_IBLB_11#1]
Dear,

I would like to extend this code to 3D for simulating moving objects. I need your email to discuss further, if you feel comfortable. contact me at [learnercfd@gmail.com](learnercfd@gmail.com). I am not familiar much with CUDA but I can manage to convert 2D into 3D. The bottleneck is to read an external mesh file as boundary in the code, for that I need your help.

Regards
Ali

**Comment by JonHall101** [comment]
I will be extending this model to 3D eventually, but only for cilia simulations.
